name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download Spacy model
        run: python -m spacy download en_core_web_sm

      - name: Run Streamlit app in the background
        run: |
          nohup streamlit run weather_bot1.py &
          sleep 10  # Sleep to ensure Streamlit starts

      - name: Verify Streamlit app is running
        run: curl -f http://localhost:8501 || exit 1

      - name: Post Set up Python
        run: echo "Post setup tasks for Python"

      - name: Post Checkout code
        run: echo "Post checkout tasks for code"
