name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set a timeout for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download Spacy model
        run: python -m spacy download en_core_web_sm

      - name: Run Streamlit app
        run: |
          set -x  # Enable shell debugging
          streamlit run weather_bot1.py --logger.level debug &
          sleep 300  # Sleep for 5 minutes to inspect the state manually

      - name: Post Set up Python
        run: echo "Post setup tasks for Python"

      - name: Post Checkout code
        run: echo "Post checkout tasks for code"
